<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<html lang="<?= htmlspecialchars($translator->getLocale(), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>">
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title><?= htmlspecialchars($translator->translate('error.500.title'), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></title>

<style>
	#nette-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
	#nette-error div { all: initial; max-width: 550px; background: white; color: #333; display: block }
	#nette-error h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
	#nette-error p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
	#nette-error small { color: gray }
</style>

<div id=nette-error>
	<div>
		<h1><?= htmlspecialchars($translator->translate('error.500.title'), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></h1>

		<p><?= htmlspecialchars($translator->translate('error.500.message'), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></p>

		<p><small><?= htmlspecialchars($translator->translate('error.code', code: 500), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></small></p>
	</div>
</div>

<script>
	document.body.insertBefore(document.getElementById('nette-error'), document.body.firstChild);
</script>
</html>
